### ISSUE TITLE
New Search Default to 'Default'

### ISSUE THREAD

**Issue by Starb7** [mountassir/ebay-search-extention#4]
Hi, I am trying your extension based on a recommendation from eBay Support.  I have it enabled and it appears to work for the first search, but subsequent searches default to 'Default Location'.  Is this a bug?

Thanks.

**Comment by mountassir** [comment]
Thanks for the ticket, I can't replicate this issue, all my searches defaults to "UK only". 

The only time this will default to "Default" (or any other option) is if you changed yourself manually, and that is by design; If you set a location manually, then the extension will not override it.

If you can replicate this, please let me know the steps.

Thanks.
