### ISSUE TITLE
Search items in EU.

### ISSUE THREAD

**Issue by michele-bs** [mountassir/ebay-search-extention#7]
Beautiful extension, thank you.

But I often want to search for items in Europe (I'm italian): in other words, I want to exclude the omnipresent China, Hong Kong etc. So it would be useful if I could set up manually the desired search area (My Country, EU, World...).

**Comment by derrickb** [comment]
Seconding this! This seems like a nearly perfect extension. The only thing missing (for me) is the ability to set the default to EU.

The rationale being: while almost all my buying is done in the UK, there are occasional items that I can only get from central EU countries, such as comics and books, so I always tick "EU" as my search location.

I wonder what this could be called in order to standardize the extension across the globe. Maybe "region"? Or "continent"? On American eBay, the next largest search area above USA is North America, while in UK it's European Union.

**Comment by mountassir** [comment]
Thanks for the feedback and the suggestion, I am looking into this.

**Comment by mountassir** [comment]
I have released a new version with this feature, thanks for your suggestion!

**Comment by michele-bs** [comment]
Wonderful.

Actually, when I search eBay, the options I can manually choose are 1. Italy, 2. EU, 3. World, and most of the times I'd like to search in EU, because buying in the USA or other Countries is due to high custom fees and I should wait lots of weeks until the delivery.

This feature makes this extention even more comfortable!
